name: Docker Build

on:
  push:
    branches: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Github Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}
      - name: Tencent Docker Login
        uses: docker/login-action@v3
        with:
          registry: hkccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_DOCKER_USERNAME }}
          password: ${{ secrets.TENCENT_DOCKER_TOKEN }}
      - name: Build dujiaoka amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/apocalypsor/dujiaoka:latest
            hkccr.ccs.tencentyun.com/apocalypsor/dujiaoka:latest
      - name: Build dujiaoka arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.arm
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/apocalypsor/dujiaoka:arm
            hkccr.ccs.tencentyun.com/apocalypsor/dujiaoka:arm
      - name: Build Epusdt
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.Epusdt
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/apocalypsor/dujiaoka:usdt
            hkccr.ccs.tencentyun.com/apocalypsor/dujiaoka:usdt

